import type { Formula } from "@/lib/schema";

export const dates3Formulas: Formula[] = [
  {
    slug: "calculate-days-between-dates",
    kind: "formula",
    title: "Calculate the Days Between Two Dates",
    seoTitle: "Days Between Two Dates in Excel & Google Sheets",
    description: "Subtract one date from another to count the days between them — order to delivery, invoice to payment, project start to finish.",
    category: "dates-deadlines",
    difficulty: "beginner",
    functions: ["DATEDIF"],
    keywords: ["days between dates", "date difference", "subtract dates", "count days", "days between two dates"],
    problem: "You have two date columns — order date and delivery date, invoice sent and invoice paid — and need the number of days between them for every row.",
    quickFormula: "=B2-A2",
    excelFormula: "=B2-A2",
    sheetsFormula: null,
    explanation: "Spreadsheets store every date as a serial number counting days since a fixed start point, so subtracting two dates gives the whole days between them — no function needed. An order placed 10 June and delivered 8 July is simply 28. The result excludes the start date and includes the end date, which is what most people expect for elapsed time. If you prefer an explicit function, =DATEDIF(A2,B2,\"D\") returns the identical day count and reads more clearly in an audit. Just keep the earlier date in A2: subtracting the wrong way round gives a negative number, and DATEDIF with reversed dates errors with #NUM!.",
    steps: [
      { part: "B2", meaning: "The later date — delivery, payment, completion." },
      { part: "-A2", meaning: "Subtracts the earlier date. Dates are numbers, so the result is the day gap." },
    ],
    whenToUse: "Use it for order-to-delivery time, days from invoice to payment, project duration, or ticket age — any \"how long did it take?\" question between two recorded dates.",
    commonMistakes: [
      { mistake: "The result shows a date like 1/28/1900 instead of 28.", fix: "The cell inherited date formatting. Switch its number format to General or Number — the math was right all along." },
      { mistake: "One of the dates is text.", fix: "\"July 8\" typed as text makes the subtraction fail with #VALUE!. Re-enter it as a real date or convert with DATEVALUE." },
      { mistake: "Expecting business days.", fix: "Plain subtraction counts every calendar day, weekends included. For working days only, use =NETWORKDAYS(A2,B2) instead." },
    ],
    sampleInput: {
      columns: ["Order", "Ordered", "Delivered"],
      rows: [
        ["ORD-101", "2026-06-10", "2026-07-08"],
        ["ORD-102", "2026-06-28", "2026-07-05"],
      ],
    },
    sampleOutput: {
      columns: ["Order", "Days to Deliver"],
      rows: [
        ["ORD-101", "28"],
        ["ORD-102", "7"],
      ],
      highlightColumn: 1,
    },
    related: ["calculate-days-overdue", "calculate-days-remaining", "calculate-years-between-dates"],
    lastReviewed: "2026-07-09",
    published: true,
    verification: {
      sheets: {
        Sheet1: [
          ["Ordered", "Delivered", "Days", "DATEDIF"],
          ["2026-06-10", "2026-07-08", "=B2-A2", '=DATEDIF(A2,B2,"D")'],
          ["2026-06-28", "2026-07-05", "=B3-A3", '=DATEDIF(A3,B3,"D")'],
          ["2026-07-01", "2026-07-01", "=B4-A4", null],
        ],
      },
      expect: [
        { cell: "C2", value: 28 },
        { cell: "D2", value: 28 },
        { cell: "C3", value: 7 },
        { cell: "D3", value: 7 },
        { cell: "C4", value: 0 },
      ],
    },
  },
  {
    slug: "business-days-between-dates",
    kind: "formula",
    title: "Count Business Days Between Two Dates",
    seoTitle: "NETWORKDAYS: Business Days Between Dates (Excel)",
    description: "NETWORKDAYS counts only Monday-to-Friday days between two dates — the right math for SLAs, payment terms, and turnaround times.",
    category: "dates-deadlines",
    difficulty: "beginner",
    functions: ["NETWORKDAYS"],
    keywords: ["business days between dates", "networkdays", "working days", "weekdays between dates", "exclude weekends"],
    problem: "Your turnaround targets are measured in working days, not calendar days — a quote answered in \"5 business days\" — so weekend days between the two dates must not count.",
    quickFormula: "=NETWORKDAYS(A2,B2)",
    excelFormula: "=NETWORKDAYS(A2,B2)",
    sheetsFormula: null,
    explanation: "NETWORKDAYS walks from the start date to the end date and counts only Mondays through Fridays, skipping every Saturday and Sunday automatically. The count is inclusive of both endpoints when they fall on weekdays — Wednesday 1 July to Wednesday 8 July is 6 business days, not 5, so subtract 1 if you want days elapsed rather than days touched. An optional third argument takes a range of holiday dates to exclude as well: =NETWORKDAYS(A2,B2,$D$2:$D$5) skips any listed holiday that falls in the window. It works identically in Excel and Google Sheets.",
    steps: [
      { part: "A2", meaning: "The start date." },
      { part: "B2", meaning: "The end date — must be on or after the start date for a positive count." },
      { part: "$D$2:$D$5 (optional)", meaning: "A list of holiday dates to exclude, anchored with $ so it stays fixed when copied down." },
    ],
    whenToUse: "Use it to measure quote turnaround, support-ticket resolution in working days, invoice processing time, or how many working days a project phase consumed.",
    commonMistakes: [
      { mistake: "Off-by-one surprise: same-week Monday to Friday returns 5, not 4.", fix: "NETWORKDAYS counts both endpoints. For working days *between* two dates exclusive of the start, use =NETWORKDAYS(A2,B2)-1." },
      { mistake: "Typing holidays directly into the formula.", fix: 'The third argument wants date values, not text like "July 3". Put holidays in cells and reference the range: =NETWORKDAYS(A2,B2,$D$2:$D$5).' },
      { mistake: "Start and end reversed.", fix: "NETWORKDAYS(B2,A2) with a later start returns a negative count. Keep the earlier date first, or wrap in ABS if row order varies." },
    ],
    sampleInput: {
      columns: ["Ticket", "Opened", "Closed"],
      rows: [
        ["T-201", "2026-07-01", "2026-07-08"],
        ["T-202", "2026-06-30", "2026-07-14"],
      ],
    },
    sampleOutput: {
      columns: ["Ticket", "Business Days"],
      rows: [
        ["T-201", "6"],
        ["T-202", "11"],
      ],
      highlightColumn: 1,
    },
    related: ["calculate-days-overdue", "calculate-invoice-due-date", "flag-overdue-tasks"],
    lastReviewed: "2026-07-09",
    published: true,
    verification: {
      sheets: {
        Sheet1: [
          ["Opened", "Closed", "BizDays", "Holiday", "WithHoliday"],
          ["2026-07-01", "2026-07-08", "=NETWORKDAYS(A2,B2)", "2026-07-03", "=NETWORKDAYS(A2,B2,D2)"],
          ["2026-06-30", "2026-07-14", "=NETWORKDAYS(A3,B3)", null, null],
        ],
      },
      expect: [
        { cell: "C2", value: 6 },
        { cell: "E2", value: 5 },
        { cell: "C3", value: 11 },
      ],
    },
  },
  {
    slug: "add-business-days-to-date",
    kind: "formula",
    title: "Add Business Days to a Date",
    seoTitle: "WORKDAY: Add Business Days to a Date (Excel)",
    description: "WORKDAY jumps forward a set number of working days, skipping weekends — ideal for promised ship dates and payment-terms deadlines.",
    category: "dates-deadlines",
    difficulty: "intermediate",
    functions: ["WORKDAY"],
    keywords: ["add business days", "workday function", "10 business days from date", "skip weekends", "working days deadline"],
    problem: "An order confirmed today must ship within 10 business days, or an approval is due 3 working days after submission — you need the actual calendar date that lands on.",
    quickFormula: "=WORKDAY(A2,10)",
    excelFormula: "=WORKDAY(A2,10)",
    sheetsFormula: null,
    explanation: "WORKDAY starts at the date in A2 and steps forward 10 working days, silently hopping over every Saturday and Sunday it crosses. The start date itself doesn't count as day one — from Wednesday 8 July 2026, ten business days lands on Wednesday 22 July, two full weekends skipped. A negative count steps backwards, useful for \"prepare 3 working days before the meeting.\" Like NETWORKDAYS, an optional third argument accepts a range of holiday dates to skip too. The result is a date serial number, so if you see a plain number like 46215, just format the cell as a date.",
    steps: [
      { part: "A2", meaning: "The start date. It is not counted — counting begins the next working day." },
      { part: "10", meaning: "Business days to add. Use a negative number to count backwards." },
      { part: "$D$2:$D$5 (optional)", meaning: "Holiday dates to skip in addition to weekends." },
    ],
    whenToUse: "Use it to compute promised ship dates, \"net 10 business days\" payment deadlines, review-cycle due dates, or any SLA promise expressed in working days.",
    commonMistakes: [
      { mistake: "Expecting the start date to count as day 1.", fix: "WORKDAY(A2,1) returns the *next* working day, not A2. If your policy counts the start day, use =WORKDAY(A2-1,10) — or just subtract 1 from the day count." },
      { mistake: "The result shows a number like 46215.", fix: "That's the date serial number — the formula worked. Format the cell as a date." },
      { mistake: "Company holidays are ignored.", fix: "WORKDAY only knows about weekends. List holidays in cells and pass them: =WORKDAY(A2,10,$D$2:$D$5)." },
    ],
    sampleInput: {
      columns: ["Order", "Confirmed"],
      rows: [
        ["ORD-310", "2026-07-08"],
        ["ORD-311", "2026-07-10"],
      ],
    },
    sampleOutput: {
      columns: ["Order", "Ship By (10 biz days)"],
      rows: [
        ["ORD-310", "2026-07-22"],
        ["ORD-311", "2026-07-24"],
      ],
      highlightColumn: 1,
    },
    related: ["calculate-invoice-due-date", "calculate-days-remaining", "calculate-days-overdue"],
    lastReviewed: "2026-07-09",
    published: true,
    verification: {
      sheets: {
        Sheet1: [
          ["Confirmed", "ShipBy", "PlusN", "Holiday", "WithHolidays"],
          ["2026-07-08", '=TEXT(WORKDAY(A2,10),"yyyy-mm-dd")', null, "2026-07-13", '=TEXT(WORKDAY(A2,10,D2:D3),"yyyy-mm-dd")'],
          ["2026-07-10", null, '=TEXT(WORKDAY(A3,3),"yyyy-mm-dd")', "2026-07-14", null],
          ["2026-07-31", null, '=TEXT(WORKDAY(A4,1),"yyyy-mm-dd")', null, null],
        ],
      },
      expect: [
        { cell: "B2", value: "2026-07-22" },
        { cell: "C3", value: "2026-07-15" },
        { cell: "C4", value: "2026-08-03" },
        { cell: "E2", value: "2026-07-24" },
      ],
    },
  },
  {
    slug: "get-month-name-from-date",
    kind: "formula",
    title: "Get the Month Name From a Date",
    seoTitle: "Month Name From a Date in Excel & Google Sheets",
    description: "TEXT with the \"mmmm\" format turns any date into its month name — July, not 7 — for report labels and monthly groupings.",
    category: "dates-deadlines",
    difficulty: "beginner",
    functions: ["TEXT"],
    keywords: ["month name from date", "convert date to month", "text mmmm", "month label", "get month from date"],
    problem: "Your order log has full dates, but the monthly revenue report needs a clean month label next to each row — \"July\", not \"2026-07-08\" and not just the number 7.",
    quickFormula: '=TEXT(A2,"mmmm")',
    excelFormula: '=TEXT(A2,"mmmm")',
    sheetsFormula: null,
    explanation: "TEXT formats a date using a pattern you choose, and \"mmmm\" is the code for the full month name — a date anywhere in July becomes \"July\". Use \"mmm\" for the short form \"Jul\", and \"mmmm yyyy\" for \"July 2026\" when your data spans years and July 2025 must not merge with July 2026. The catch to remember: the result is text, not a date, so it sorts alphabetically (April before February) and won't feed date math. Keep the real date column for sorting and pivots, and use the TEXT column purely as a label. MONTH(A2) is the numeric cousin — it returns 7, which sorts correctly but reads worse.",
    steps: [
      { part: "A2", meaning: "The cell holding a real date." },
      { part: '"mmmm"', meaning: 'The format code for the full month name. "mmm" gives "Jul"; "mmmm yyyy" gives "July 2026".' },
    ],
    whenToUse: "Use it to label rows for monthly sales summaries, invoice aging reports grouped by month, or dashboard headers — anywhere a human-readable month beats a raw date.",
    commonMistakes: [
      { mistake: "Sorting the month-name column and getting April, August, December…", fix: "Month names are text and sort alphabetically. Sort by the original date column instead, or keep a hidden =MONTH(A2) column for ordering." },
      { mistake: 'Using "mm" and getting 07.', fix: '"mm" is the two-digit month number (and minutes in time formats). Month *names* need three or four m\'s: "mmm" or "mmmm".' },
      { mistake: "Grouping by month name across multiple years.", fix: 'July 2025 and July 2026 both label as "July" and merge in a summary. Use =TEXT(A2,"mmmm yyyy") when the data spans years.' },
    ],
    sampleInput: {
      columns: ["Invoice", "Issued"],
      rows: [
        ["INV-901", "2026-07-08"],
        ["INV-902", "2026-02-14"],
      ],
    },
    sampleOutput: {
      columns: ["Invoice", "Month"],
      rows: [
        ["INV-901", "July"],
        ["INV-902", "February"],
      ],
      highlightColumn: 1,
    },
    related: ["summarize-by-month", "group-dates-by-month", "calculate-years-between-dates"],
    lastReviewed: "2026-07-09",
    published: true,
    // TEXT(...,"mmmm") is correct in Excel & Sheets, but our engine's TEXT
    // lacks month-name format tokens — so the engine verifies the same
    // date→month-name mapping via MONTH + CHOOSE instead.
    verification: {
      sheets: {
        Sheet1: [
          ["Issued", "MonthNum", "MonthName"],
          ["2026-07-08", "=MONTH(A2)", '=CHOOSE(MONTH(A2),"January","February","March","April","May","June","July","August","September","October","November","December")'],
          ["2026-02-14", "=MONTH(A3)", '=CHOOSE(MONTH(A3),"January","February","March","April","May","June","July","August","September","October","November","December")'],
        ],
      },
      expect: [
        { cell: "B2", value: 7 },
        { cell: "C2", value: "July" },
        { cell: "B3", value: 2 },
        { cell: "C3", value: "February" },
      ],
    },
  },
  {
    slug: "get-quarter-from-date",
    kind: "formula",
    title: "Get the Quarter From a Date",
    seoTitle: "Quarter From a Date Formula (Excel & Sheets)",
    description: "Turn any date into Q1–Q4 with one formula — divide the month by 3 and round up — for quarterly sales, pipeline, and budget rollups.",
    category: "dates-deadlines",
    difficulty: "intermediate",
    functions: ["ROUNDUP", "MONTH"],
    keywords: ["quarter from date", "convert date to quarter", "q1 q2 q3 q4", "fiscal quarter formula", "quarterly report"],
    problem: "Deals close on specific dates, but the pipeline review rolls everything up by quarter — each close date needs a Q1, Q2, Q3, or Q4 label.",
    quickFormula: '="Q"&ROUNDUP(MONTH(A2)/3,0)',
    excelFormula: '="Q"&ROUNDUP(MONTH(A2)/3,0)',
    sheetsFormula: null,
    explanation: "MONTH pulls the month number from the date, and dividing by 3 maps months onto quarters: July is 7 ÷ 3 = 2.33, and ROUNDUP takes that to 3 — third quarter. The trick works for every month: 1–3 round up to 1, 4–6 to 2, 7–9 to 3, 10–12 to 4. Gluing \"Q\" on the front with & produces the familiar Q3 label. This assumes calendar quarters starting in January; if your fiscal year starts in another month, shift the month number before dividing, or use a small 12-row lookup table, which is easier to audit.",
    steps: [
      { part: "MONTH(A2)", meaning: "The month number, 1–12." },
      { part: "/3", meaning: "Maps months onto quarter boundaries: 2.33 for July." },
      { part: "ROUNDUP(…,0)", meaning: "Rounds up to the whole quarter number, 1–4." },
      { part: '"Q"&', meaning: 'Prefixes the number so the cell reads "Q3".' },
    ],
    whenToUse: "Use it to tag deals by close quarter, group invoices for quarterly VAT or sales-tax filings, or build quarter columns for pivot tables and budget-versus-actual reports.",
    commonMistakes: [
      { mistake: "Using ROUND instead of ROUNDUP.", fix: "ROUND(7/3,0) is 2, putting July in Q2. Only ROUNDUP maps the month ranges correctly — the round *up* is the whole mechanism." },
      { mistake: "Company fiscal year doesn't start in January.", fix: "This formula gives calendar quarters. If FY starts in July, July must be Q1 — shift the month before dividing or use a 12-row lookup table." },
      { mistake: "Grouping by quarter across years.", fix: 'Q3 2025 and Q3 2026 merge into one bucket. Include the year: ="Q"&ROUNDUP(MONTH(A2)/3,0)&" "&YEAR(A2).' },
    ],
    sampleInput: {
      columns: ["Deal", "Close Date"],
      rows: [
        ["Acme Co", "2026-02-14"],
        ["Borealis", "2026-07-08"],
        ["Cobalt", "2026-12-01"],
      ],
    },
    sampleOutput: {
      columns: ["Deal", "Quarter"],
      rows: [
        ["Acme Co", "Q1"],
        ["Borealis", "Q3"],
        ["Cobalt", "Q4"],
      ],
      highlightColumn: 1,
    },
    related: ["summarize-by-month", "group-dates-by-month", "calculate-years-between-dates"],
    lastReviewed: "2026-07-09",
    published: true,
    verification: {
      sheets: {
        Sheet1: [
          ["Close", "Quarter"],
          ["2026-02-14", '="Q"&ROUNDUP(MONTH(A2)/3,0)'],
          ["2026-04-30", '="Q"&ROUNDUP(MONTH(A3)/3,0)'],
          ["2026-07-08", '="Q"&ROUNDUP(MONTH(A4)/3,0)'],
          ["2026-12-01", '="Q"&ROUNDUP(MONTH(A5)/3,0)'],
        ],
      },
      expect: [
        { cell: "B2", value: "Q1" },
        { cell: "B3", value: "Q2" },
        { cell: "B4", value: "Q3" },
        { cell: "B5", value: "Q4" },
      ],
    },
  },
  {
    slug: "last-day-of-month",
    kind: "formula",
    title: "Find the Last Day of the Month for Any Date",
    seoTitle: "EOMONTH: Last Day of the Month (Excel & Sheets)",
    description: "EOMONTH returns the month-end date for any date — the standard tool for billing cutoffs, month-end close, and end-of-month due dates.",
    category: "dates-deadlines",
    difficulty: "beginner",
    functions: ["EOMONTH"],
    keywords: ["last day of month", "eomonth", "month end date", "end of month formula", "billing cutoff date"],
    problem: "Invoices are due at month end, reports close on the last day of the month — and that day floats between the 28th and the 31st, so you need it computed from any date.",
    quickFormula: "=EOMONTH(A2,0)",
    excelFormula: "=EOMONTH(A2,0)",
    sheetsFormula: null,
    explanation: "EOMONTH takes a date and an offset in months, then returns the last day of the resulting month. An offset of 0 means the same month — any date in July 2026 returns 31 July 2026 — and the function knows every month length, including 28-day Februaries and leap years. Change the offset to look ahead or back: =EOMONTH(A2,1) is the end of next month (a classic \"due end of following month\" payment term), and =EOMONTH(A2,-1) is the end of last month, handy for prior-period cutoffs. The result is a real date, so it plugs straight into overdue checks and countdowns.",
    steps: [
      { part: "A2", meaning: "Any date in the month you care about." },
      { part: "0", meaning: "Months to shift: 0 = this month's end, 1 = next month's end, -1 = last month's end." },
    ],
    whenToUse: "Use it for invoice due dates set to month end, billing-period cutoffs, subscription period ends, and month-end close checklists tied to the real last day.",
    commonMistakes: [
      { mistake: "Hardcoding the 30th or 31st.", fix: "=DATE(YEAR(A2),MONTH(A2),31) breaks in February, April, June, September, and November. EOMONTH always knows the real month length." },
      { mistake: "The result shows a serial number like 46224.", fix: "EOMONTH returns a date value; the cell just isn't formatted. Apply a date format." },
      { mistake: "Using 1 when you meant 0.", fix: "The second argument is an offset, not a flag. =EOMONTH(A2,1) is the end of *next* month — use 0 for the current month's end." },
    ],
    sampleInput: {
      columns: ["Invoice", "Issued"],
      rows: [
        ["INV-501", "2026-07-08"],
        ["INV-502", "2026-02-14"],
      ],
    },
    sampleOutput: {
      columns: ["Invoice", "Due (Month End)"],
      rows: [
        ["INV-501", "2026-07-31"],
        ["INV-502", "2026-02-28"],
      ],
      highlightColumn: 1,
    },
    related: ["calculate-invoice-due-date", "summarize-by-month", "calculate-days-remaining"],
    lastReviewed: "2026-07-09",
    published: true,
    verification: {
      sheets: {
        Sheet1: [
          ["Issued", "MonthEnd", "NextMonthEnd"],
          ["2026-07-08", '=TEXT(EOMONTH(A2,0),"yyyy-mm-dd")', '=TEXT(EOMONTH(A2,1),"yyyy-mm-dd")'],
          ["2026-02-14", '=TEXT(EOMONTH(A3,0),"yyyy-mm-dd")', null],
        ],
      },
      expect: [
        { cell: "B2", value: "2026-07-31" },
        { cell: "C2", value: "2026-08-31" },
        { cell: "B3", value: "2026-02-28" },
      ],
    },
  },
  {
    slug: "first-day-of-next-month",
    kind: "formula",
    title: "Get the First Day of the Next Month",
    seoTitle: "First Day of Next Month Formula (Excel & Sheets)",
    description: "EOMONTH plus one day lands on the 1st of the following month — the clean way to compute billing starts and new-period kickoff dates.",
    category: "dates-deadlines",
    difficulty: "intermediate",
    functions: ["EOMONTH"],
    keywords: ["first day of next month", "next month start date", "billing period start", "eomonth plus 1", "first of the month formula"],
    problem: "A subscription signed mid-month starts billing on the 1st of the next month, or a project phase kicks off at the next month boundary — you need that exact date from any signup date.",
    quickFormula: "=EOMONTH(A2,0)+1",
    excelFormula: "=EOMONTH(A2,0)+1",
    sheetsFormula: null,
    explanation: "EOMONTH(A2,0) finds the last day of the date's month, and adding 1 steps over the boundary to the 1st of the next month — 8 July 2026 becomes 31 July, plus one day is 1 August. Because dates are numbers, the +1 is ordinary arithmetic, and it handles every edge automatically: month lengths, year-end (15 December rolls to 1 January 2027), and leap Februaries. The same pattern generalizes — =EOMONTH(A2,1)+1 gives the 1st of the month after next, and =EOMONTH(A2,-1)+1 gives the 1st of the *current* month, useful as a period-start anchor in reports.",
    steps: [
      { part: "EOMONTH(A2,0)", meaning: "The last day of A2's month — e.g. 2026-07-31." },
      { part: "+1", meaning: "One day past month end is always the 1st of the next month." },
    ],
    whenToUse: "Use it for subscription billing starts, rent or lease periods beginning on the 1st, contract effective dates at the next month boundary, and report period anchors.",
    commonMistakes: [
      { mistake: "Putting the +1 inside EOMONTH.", fix: "=EOMONTH(A2,0+1) or =EOMONTH(A2,1) returns the end of *next* month. The +1 must sit outside the function, adding one day to the month-end date." },
      { mistake: "Building it with DATE(YEAR(A2),MONTH(A2)+1,1) and worrying about December.", fix: "That version actually works — DATE rolls month 13 into January — but it's longer and easier to mistype. EOMONTH(A2,0)+1 is the idiomatic form." },
      { mistake: "The result shows a number like 46235.", fix: "That's the date serial — format the cell as a date to see 2026-08-01." },
    ],
    sampleInput: {
      columns: ["Customer", "Signed Up"],
      rows: [
        ["Ana Torres", "2026-07-08"],
        ["Ben Okafor", "2026-12-15"],
      ],
    },
    sampleOutput: {
      columns: ["Customer", "Billing Starts"],
      rows: [
        ["Ana Torres", "2026-08-01"],
        ["Ben Okafor", "2027-01-01"],
      ],
      highlightColumn: 1,
    },
    related: ["summarize-by-month", "group-dates-by-month", "calculate-invoice-due-date"],
    lastReviewed: "2026-07-09",
    published: true,
    verification: {
      sheets: {
        Sheet1: [
          ["SignedUp", "BillingStart"],
          ["2026-07-08", '=TEXT(EOMONTH(A2,0)+1,"yyyy-mm-dd")'],
          ["2026-12-15", '=TEXT(EOMONTH(A3,0)+1,"yyyy-mm-dd")'],
          ["2026-02-14", '=TEXT(EOMONTH(A4,0)+1,"yyyy-mm-dd")'],
        ],
      },
      expect: [
        { cell: "B2", value: "2026-08-01" },
        { cell: "B3", value: "2027-01-01" },
        { cell: "B4", value: "2026-03-01" },
      ],
    },
  },
  {
    slug: "check-if-date-is-weekend",
    kind: "formula",
    title: "Check Whether a Date Falls on a Weekend",
    seoTitle: "Weekend Check With WEEKDAY (Excel & Sheets)",
    description: "WEEKDAY with return type 2 numbers the week Monday=1 to Sunday=7, so anything above 5 is a weekend — one IF turns that into a label.",
    category: "dates-deadlines",
    difficulty: "beginner",
    functions: ["WEEKDAY", "IF"],
    keywords: ["check if date is weekend", "weekday function", "weekend or weekday", "date falls on saturday sunday", "flag weekend dates"],
    problem: "Delivery dates, payment run dates, or scheduled go-lives sometimes land on a Saturday or Sunday — and you need each row flagged before someone promises a weekend delivery.",
    quickFormula: '=IF(WEEKDAY(A2,2)>5,"Weekend","Weekday")',
    excelFormula: '=IF(WEEKDAY(A2,2)>5,"Weekend","Weekday")',
    sheetsFormula: null,
    explanation: "WEEKDAY returns which day of the week a date is, as a number, and the second argument picks the numbering scheme. Type 2 is the tidy one: Monday=1 through Sunday=7, so Saturday and Sunday are exactly the values above 5, and one comparison catches both. The IF then translates the test into a readable label. Without the second argument, WEEKDAY defaults to type 1 — Sunday=1 through Saturday=7 — where the weekend sits awkwardly at both ends (1 and 7) and a single > test can't isolate it. That default is the source of most broken weekend checks.",
    steps: [
      { part: "WEEKDAY(A2,2)", meaning: "Day number with Monday=1 … Sunday=7." },
      { part: ">5", meaning: "TRUE only for 6 (Saturday) and 7 (Sunday)." },
      { part: '"Weekend","Weekday"', meaning: "The labels to show. Swap in whatever your report needs." },
    ],
    whenToUse: "Use it to audit delivery schedules, block payment runs from landing on weekends, sanity-check go-live dates, or drive conditional formatting that tints weekend rows.",
    commonMistakes: [
      { mistake: "Leaving out the return type.", fix: "=WEEKDAY(A2)>5 uses Sunday=1 numbering, so Sundays return 1 and slip through as \"Weekday\". Always pass 2 as the second argument for this test." },
      { mistake: "Rebuilding the test as two comparisons.", fix: "=IF(OR(WEEKDAY(A2)=1,WEEKDAY(A2)=7),…) works but is longer and easier to get wrong. WEEKDAY(A2,2)>5 does it in one clean comparison." },
      { mistake: "Needing to *move* the date, not just flag it.", fix: "This formula only labels. To shift a weekend date to the next working day, use =WORKDAY(A2-1,1), which returns A2 itself when it's already a weekday." },
    ],
    sampleInput: {
      columns: ["Shipment", "Scheduled"],
      rows: [
        ["SHP-701", "2026-07-08"],
        ["SHP-702", "2026-07-11"],
        ["SHP-703", "2026-07-12"],
      ],
    },
    sampleOutput: {
      columns: ["Shipment", "Day Check"],
      rows: [
        ["SHP-701", "Weekday"],
        ["SHP-702", "Weekend"],
        ["SHP-703", "Weekend"],
      ],
      highlightColumn: 1,
    },
    related: ["flag-overdue-tasks", "calculate-days-remaining", "calculate-days-overdue"],
    lastReviewed: "2026-07-09",
    published: true,
    verification: {
      sheets: {
        Sheet1: [
          ["Scheduled", "DayNum", "Check"],
          ["2026-07-08", "=WEEKDAY(A2,2)", '=IF(WEEKDAY(A2,2)>5,"Weekend","Weekday")'],
          ["2026-07-11", "=WEEKDAY(A3,2)", '=IF(WEEKDAY(A3,2)>5,"Weekend","Weekday")'],
          ["2026-07-12", "=WEEKDAY(A4,2)", '=IF(WEEKDAY(A4,2)>5,"Weekend","Weekday")'],
          ["2026-07-13", "=WEEKDAY(A5,2)", '=IF(WEEKDAY(A5,2)>5,"Weekend","Weekday")'],
        ],
      },
      expect: [
        { cell: "B2", value: 3 },
        { cell: "C2", value: "Weekday" },
        { cell: "B3", value: 6 },
        { cell: "C3", value: "Weekend" },
        { cell: "C4", value: "Weekend" },
        { cell: "C5", value: "Weekday" },
      ],
    },
  },
];
